In [12]:
import numpy as np
import pandas as pd

In [4]:
a1 = np.array([1,2,3])

In [5]:
a1

array([1, 2, 3])

In [8]:
a2 = np.array([
    [1,2,3],
    [1.1,2.2,3.3]
])

In [9]:
a2

array([[1. , 2. , 3. ],
       [1.1, 2.2, 3.3]])

In [10]:
a3 = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
[[10,11,12],
  [13,14,15],
    [16,17,18]]
])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.0
1  1.1  2.2  3.3

In [16]:
ones = np.ones((3,3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])